# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e15de0a525a80248522240dd72d104963a9deb1ce55b68eb3de8114243ff29f793b5c2bcf8a41f867c7c9b7e4e5072963f3457677fa58178283f80a41ef4e2ea

test:
  secret_key_base: 338c8126f1ab7056bab720ba07937befd7436a259ef7dad70e11cbe7bc857cf4610f7116ef323195841b6faa08f57cd5c22a2f3d180a3ea852a7416bb55961cc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
